CREATE OR REPLACE TYPE TYP_BINDS_REC AS OBJECT
(
   BIND_POSITION       INTEGER,
   BIND_VALUE_NUMBER   NUMBER,
   BIND_VALUE_VARCHAR2 VARCHAR2(4000),
   BIND_VALUE_DATE     DATE,
   CONSTRUCTOR FUNCTION TYP_BINDS_REC RETURN SELF AS RESULT
)
;
/
CREATE OR REPLACE TYPE BODY TYP_BINDS_REC IS

   -- Member procedures and functions
   CONSTRUCTOR FUNCTION TYP_BINDS_REC RETURN SELF AS RESULT IS
   BEGIN
   
      SELF.BIND_POSITION       := NULL;
      SELF.BIND_VALUE_NUMBER   := NULL;
      SELF.BIND_VALUE_DATE     := NULL;
      SELF.BIND_VALUE_VARCHAR2 := NULL;
   
      RETURN;
   
   END;

END;
/
